/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Video = {
  _id: string
  _type: 'video'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  url?: string
  mimeType?: string
  poster?: ImagePlacement
  sourceKey?: string
}

export type PhotographReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'photograph'
}

export type ImagePlacement = {
  _type: 'imagePlacement'
  photograph?: PhotographReference
  alt?: string
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: RichText
  order?: number
  sourceKey?: string
}

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h3' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type TeamGroupReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'teamGroup'
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  name?: string
  role?: string
  teamGroup?: TeamGroupReference
  bio?: RichText
  shortBio?: RichText
  portrait?: ImagePlacement
  order?: number
  sourceKey?: string
}

export type TeamGroup = {
  _id: string
  _type: 'teamGroup'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
}

export type NotFoundPage = {
  _id: string
  _type: 'notFoundPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: ImagePlacement
}

export type PrivacyPage = {
  _id: string
  _type: 'privacyPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type PressPage = {
  _id: string
  _type: 'pressPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type MediaPage = {
  _id: string
  _type: 'mediaPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type InvolvementPage = {
  _id: string
  _type: 'involvementPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type ChaptersPage = {
  _id: string
  _type: 'chaptersPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  route?: string
  seo?: Seo
  sections?: Array<
    {
      _key: string
    } & ContentSection
  >
  featuredImages?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceKey?: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  alternateName?: string
  description?: string
  productionCompany?: string
  email?: string
  releaseLabel?: string
  defaultImage?: ImagePlacement
  primaryNavigation?: Array<
    {
      _key: string
    } & SiteLink
  >
  footerNavigation?: Array<
    {
      _key: string
    } & SiteLink
  >
  socialLinks?: Array<
    {
      _key: string
    } & SiteLink
  >
  sourceKey?: string
}

export type ContentSection = {
  _type: 'contentSection'
  label?: string
  heading?: string
  eyebrow?: string
  body?: RichText
  links?: Array<
    {
      _key: string
    } & SiteLink
  >
  images?: Array<
    {
      _key: string
    } & ImagePlacement
  >
  sourceSelector?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ChapterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'chapter'
}

export type Photograph = {
  _id: string
  _type: 'photograph'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
  caption?: string
  credit?: string
  rights?: string
  chapter?: ChapterReference
  gallery?: boolean
  order?: number
  sourcePaths?: Array<string>
  sourceKey?: string
}

export type OrganizationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'organization'
}

export type Chapter = {
  _id: string
  _type: 'chapter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  number?: number
  title?: string
  community?: string
  eyebrow?: string
  slug?: Slug
  summary?: string
  story?: RichText
  environmentalFocus?: RichText
  productionNote?: RichText
  region?: string
  elevation?: string
  location?: string
  locationDescription?: RichText
  themes?: Array<string>
  hero?: ImagePlacement
  portrait?: ImagePlacement
  landscape?: ImagePlacement
  organization?: OrganizationReference
  seo?: Seo
  sourceKey?: string
}

export type Organization = {
  _id: string
  _type: 'organization'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  name?: string
  category?: string
  place?: string
  description?: RichText
  location?: Geopoint
  image?: ImagePlacement
  link?: SiteLink
  linkNote?: string
  status?: 'current' | 'historical'
  order?: number
  sourceKey?: string
}

export type SiteLink = {
  _type: 'siteLink'
  label?: string
  href?: string
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | Video
  | PhotographReference
  | ImagePlacement
  | Faq
  | RichText
  | TeamGroupReference
  | Person
  | TeamGroup
  | NotFoundPage
  | Seo
  | PrivacyPage
  | PressPage
  | ContactPage
  | MediaPage
  | InvolvementPage
  | ChaptersPage
  | AboutPage
  | HomePage
  | SiteSettings
  | ContentSection
  | SanityImageAssetReference
  | ChapterReference
  | Photograph
  | OrganizationReference
  | Chapter
  | Organization
  | SiteLink
  | Geopoint
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
